### ISSUE TITLE
2018 roadmap

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#139]
These are the milestones, in order, I would like to achieve in this project by the end of 2018.

- [x] Use SQLite
- [x] Replace transaction log based sync with state-based sync (1)
- [x] End-to-end encryption of notes and all other user data (2)
- [x] Open source the server and web client (3)

(1) - Currently sync works by keeping a log of all actions (add note, edit note, delete note, add book, delete book). This proved to be prone to edge cases and hard to extend. Work is under the way to implement a state-based replication from the server to the client.

(2), (3) - I would like Dnote to be a free software (libre not gratis) putting users' privacy first. In order to open source the server-side, I feel that e2e encryption of user data must come first because respecting the users' privacy is higher priority and encryption will mitigate possible security concerns resulting from open sourcing the product.

Feedback is welcomed.

**Comment by sergeevabc** [comment]
Portability would be appreciated as well,
i.e. look for ```dnote.db``` and ```dnoterc``` nearby first not to pollute ```C:\Users\USERNAME\```

**Comment by sungwoncho** [comment]
end-to-end encryption was shipped with [v0.6.0](https://github.com/dnote/cli/releases/tag/v0.6.0).

**Comment by sungwoncho** [comment]
The server and the web client were open sourced by #171. Late by 5 months, but the goals for 2018 have been achieved.
